apiVersion : apps/v1
kind: Deployment
metadata:
  name: jenkins
  labels:
    project: jenkins
spec:
  selector:
    matchLabels:
      app: jenkins
  template:
    metadata:
      labels:
        app: jenkins
    spec:
      containers:
        - name : jenkins
          image: jenkins:2.60.3
          ports:
            - containerPort: 8080
