apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: jenkins-ingress

spec:
  ingressClassName: nginx
  rules:
    - host: jenkins.loc
      http:
        paths:
          - backend:
              serviceName: jenkins-service
              servicePort: 8080
