apiVersion: v1
kind: Service
metadata:
  name: jenkins-service
  labels:
    env  : prod
spec:
  type: NodePort
  selector:
    project: jenkins
  ports:
    - name      : jenkins
      protocol  : TCP
      port      : 8080
      targetPort: 8080
