---
- hosts: k8cluster
  remote_user: root

  tasks:
    - name: Create source dir
      file:
        path: '~/grafana'
        state: directory

    # Copying the Pod.yaml and deployment.yaml in the remote node.
    - name: "Copying files"
      template:
        src: '../../grafana/{{ item }}.yaml'
        dest: '~/grafana/{{ item }}.yaml'
      loop:
        - 'deployment'
        - 'service'

    - name: Create deployment
      k8s:
        state: present
        src: '~/grafana/deployment.yaml'

    - name: Create service
      k8s:
        state: present
        src: '~/grafana/service.yaml'
